### PR TITLE
requirements draft

### PR DESCRIPTION
**Pull request by XueyangLiu1**

### CODE REVIEW

**Review by Ericlogin — COMMENTED** [review]
1

**Review by luciferlys — APPROVED** [review]
This txt file looks fine for me. I think we can merge it first.

**Review by luciferlys — CHANGES_REQUESTED** [review]
I'm not sure if we have to ignore the `.idea` folder since it is generated by IDEA automatically and may change every single time.

**Comment by XueyangLiu1** [comment]
Try my branch on your own computer and open MonopolyGame with intellij idea. 
Let's see if the proj can be composed up by using that pom.xml, if that works, then we don't need to track .idea and target(build out files) directories in our git repo. 
BTW, I am using jdk azul-18(Azul Zulu version 18.0.2) on my pc

**Comment by XueyangLiu1** [comment]
I've verified that the proj can be built and run smoothly on my mbp

**Review by Ericlogin — APPROVED** [review]

**Review by luciferlys — APPROVED** [review]
Looks great, pr approved.

**Pull request merged**
